apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: post-disaster-alert
  labels:
    app.kubernetes.io/name: post-disaster-alert
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
