apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: post-disaster-alert
  namespace: post-disaster-alert
  labels:
    app.kubernetes.io/name: post-disaster-alert
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: post-disaster-alert
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
