apiVersion: v1
kind: ResourceQuota
metadata:
  name: post-disaster-alert
  namespace: post-disaster-alert
  labels:
    app.kubernetes.io/name: post-disaster-alert
spec:
  hard:
    pods: "12"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
